definitions:
  controllers.CreateHelpReq:
    properties:
      content:
        type: string
      hid:
        type: integer
      title:
        type: string
    type: object
  controllers.ReqLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.Result:
    properties:
      code:
        example: 0
        type: integer
      data:
        type: object
      message:
        example: 请求信息
        type: string
    type: object
  models.UserInfo:
    properties:
      email:
        type: string
      intro:
        type: string
      phone:
        type: string
      status:
        type: string
      uid:
        type: integer
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /dashboard:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      tags:
      - dashboard
  /getIndex:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      responses: {}
      summary: 获取首页信息
      tags:
      - index
  /help:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      tags:
      - help
      - accounts
    post:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 显示网站信息
      tags:
      - help
  /help/detail/:hid:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 显示帮助详情
      tags:
      - help
  /help/operate:
    post:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 显示网站信息
      tags:
      - help
  /help/store:
    post:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.CreateHelpReq'
      summary: 新增帮助保存
      tags:
      - accounts
  /json:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: json 格式化
      tags:
      - app
  /logout:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 退出登录
      tags:
      - accounts
  /organize/detail/:oid:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 保存修改信息
      tags:
      - organize
  /organize/join:
    post:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 加入组织
      tags:
      - organize
  /organize/list:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 获取项目列表
      tags:
      - accounts
  /person:
    post:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 个人中心
      tags:
      - accounts
  /person/check:
    post:
      consumes:
      - application/json
      description: 资料检查
      parameters:
      - description: 用户验证
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.UserInfo'
      produces:
      - application/json
      summary: 个人资料检查,检查时只会一次传一个字段
      tags:
      - accounts
  /person/store:
    post:
      consumes:
      - application/json
      description: 描述信息
      parameters:
      - description: 用户验证
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.UserInfo'
      produces:
      - application/json
      summary: 个人资料修改
      tags:
      - accounts
  /userlogin:
    post:
      consumes:
      - application/json
      description: 描述信息
      parameters:
      - description: login
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Result'
      summary: 登陆
      tags:
      - accounts
  /users/detail/:userid:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 用户详情
      tags:
      - accounts
  /users/list:
    get:
      consumes:
      - application/json
      description: 描述信息
      produces:
      - application/json
      summary: 获取用户列表页（组织成员）
      tags:
      - accounts
swagger: "2.0"
